version: '3.8'
services:
  securebase-server:
    build:
      context: ./packages/server
    container_name: server
    volumes:
      - ./packages/server:/src
      # - ./yarn.lock:/src/yarn.lock
    ports:
      - '4000:4000'
    depends_on:
      - postgres
      - dynamodb
    environment:
      - AWS_ACCESS_KEY_ID=''
      - AWS_SECRET_ACCESS_KEY=''
      - REGION='eu-west-1'
    env_file:
      - ./.env
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - '8000:8000'
  postgres:
    image: postgres:11-alpine
    ports:
      - 5433:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      TZ: 'Asia/Tokyo'
